
package cn.gov.zh;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "uaService", targetNamespace = "http://zh.gov.cn", wsdlLocation = "http://ca.zhwsbs.gov.cn:82/UaCommonService2.0/uaService?WSDL")
public class UaService
    extends Service
{

    private final static URL UASERVICE_WSDL_LOCATION;
    private final static WebServiceException UASERVICE_EXCEPTION;
    private final static QName UASERVICE_QNAME = new QName("http://zh.gov.cn", "uaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ca.zhwsbs.gov.cn:82/UaCommonService2.0/uaService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UASERVICE_WSDL_LOCATION = url;
        UASERVICE_EXCEPTION = e;
    }

    public UaService() {
        super(__getWsdlLocation(), UASERVICE_QNAME);
    }

    public UaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UASERVICE_QNAME, features);
    }

    public UaService(URL wsdlLocation) {
        super(wsdlLocation, UASERVICE_QNAME);
    }

    public UaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UASERVICE_QNAME, features);
    }

    public UaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UaWebServiceSoap
     */
    @WebEndpoint(name = "uaWebServiceSoap")
    public UaWebServiceSoap getUaWebServiceSoap() {
        return super.getPort(new QName("http://zh.gov.cn", "uaWebServiceSoap"), UaWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UaWebServiceSoap
     */
    @WebEndpoint(name = "uaWebServiceSoap")
    public UaWebServiceSoap getUaWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://zh.gov.cn", "uaWebServiceSoap"), UaWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UASERVICE_EXCEPTION!= null) {
            throw UASERVICE_EXCEPTION;
        }
        return UASERVICE_WSDL_LOCATION;
    }

}
