
package cn.gov.zh;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "uaWebServiceSoap", targetNamespace = "http://zh.gov.cn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UaWebServiceSoap {


    /**
     * Ticket≤È—Ø(∆Û“µ)
     * 
     * @param parameters
     * @return
     *     returns cn.gov.zh.QueryTicketInfoNewResponse
     */
    @WebMethod(operationName = "QueryTicketInfoNew", action = "http://zh.gov.cn/QueryTicketInfoNew")
    @WebResult(name = "QueryTicketInfoNewResponse", targetNamespace = "http://zh.gov.cn", partName = "parameters")
    public QueryTicketInfoNewResponse queryTicketInfoNew(
        @WebParam(name = "QueryTicketInfoNewRequest", targetNamespace = "http://zh.gov.cn", partName = "parameters")
        QueryTicketInfoNewRequest parameters);

}
